Changes to be committed: 	modified:   src/main.py
DONE:

redeclare variables in async main, because it could't reach the ones declared in the regular main function,
even when they were defined as globals.

WHY:

Executing
`(subreddits) PS C:/projects/subreddits>  python src/main.py -e`

returns the ERROR:

```shell
[i] Asking permissions for your account(s)...
Version 7.5.0 of asyncpraw is outdated. Version 7.8.1 was released Saturday December 21, 2024.
[i] Permissions granted.

Traceback (most recent call last):
  File "H:\Users\Tom\projects\backup_reddit_account_tomwwabo\subreddits\src\main.py", line 258, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "H:\Users\Tom\projects\backup_reddit_account_tomwwabo\subreddits\src\main.py", line 226, in main
    if export_subs or restore or one:
UnboundLocalError: local variable 'export_subs' referenced before assignment
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000207EB0D0BE0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000207EB0723A0>, 23579.046)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000207EB0D0AF0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000207EB059850>
transport: <_ProactorSocketTransport fd=752 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x00000207E86C19D0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 599, in _start_shutdown
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 604, in _write_appdata
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\sslproto.py", line 726, in _fatal_error
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Users\user\AppData\Roaming\uv\python\cpython-3.9.23-windows-x86_64-none\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```